# Makefile
# capp-build
#
# Build orchestration, gate testing, and release tooling.
#
# One-time environment setup, required for resolving the private capp-parse
# module (symptoms of their absence are noted):
#
#   go env -w GOPRIVATE=github.com/enquora-net/*
#       Keeps proxy.golang.org and sum.golang.org out of the resolution path.
#       Absent: fetch errors mentioning proxy.golang.org (404/410).
#
#   git config --global url."git@github.com:enquora-net/".insteadOf "https://github.com/enquora-net/"
#       Routes module fetches for the org over SSH.
#       Absent: "terminal prompts disabled" / "could not read Username".
#
# Updating the capp-parse pin (make bump-parse):
#   Pinning is by commit hash; the branch is irrelevant. Go resolves any
#   pushed commit by hash. Never pin @latest or @branch — those consult the
#   default branch and caching makes them non-deterministic.
#
# Release workflow (make release):
#   1. Update VERSION.txt and CHANGELOG.md.
#   2. Commit and push.
#   3. Run `make release`.
#   Requires: gh (GitHub CLI), authenticated with repo write access.
#
# Cross-compilation:
#   capp-parse/grammar requires CGO_ENABLED=1 due to go-tree-sitter's
#   sitter.Language type.
#
#   macOS targets: built with the native host toolchain (CGO_ENABLED=1,
#   no wrapper).  Zig does not ship macOS SDK system libraries (libresolv
#   etc.) so cross-compiling macOS→macOS via Zig fails at link time.
#   darwin/arm64 and darwin/amd64 are both produced on the ARM64 host via
#   GOARCH override; the native clang handles both architectures.
#
#   Linux and Windows targets: built via zig cc wrappers.  Zig provides
#   hermetic C cross-compilation for these targets without per-platform
#   toolchain installation.  Linux targets pin glibc 2.28 for broad
#   distribution compatibility.
#
# Version embedding:
#   Lisette has no mutable package-level vars, so ldflags injection is not
#   viable.  `make gen-version` writes src/version_generated.lis containing
#   a pub const VERSION before lis emit runs.
#
# Portability: this Makefile assumes a POSIX shell. The durable home for
# this orchestration is the cappuccino CLI; the Makefile is development
# scaffolding until then.

BINARY       := capp-build
TARGET       := target
BUILD_DIR    := build-artifacts
WRAPPERS_DIR := build-wrappers
PARSE_DIR    := $(HOME)/Desktop/capp-parse
PARSE_MODULE := github.com/enquora-net/capp-parse

TOOLCHAIN_TEST := $(HOME)/Desktop/toolchain_test
TOOLCHAIN_REF  := $(HOME)/Desktop/toolchain_reference

VERSION      := $(shell head -1 VERSION.txt)
COMMIT       := $(shell git rev-parse --short HEAD)
VERSION_FILE := src/version_generated.lis

.PHONY: all run gen-version emit build-host build-all release checksums \
	restore-version clean bump-parse gate gate-release gate-archive

all: run

run:
	lis run

gen-version:
	@printf '//**\n// version_generated.lis\n// capp-build\n//\n// Generated by `make emit` — do not edit by hand.\n// **\n\npub const VERSION: string = "$(VERSION) ($(COMMIT))"\n' \
		> "$(VERSION_FILE)"
	@echo "version: $(VERSION) ($(COMMIT))"

restore-version:
	@printf '//**\n// version_generated.lis\n// capp-build\n//\n// Generated by `make emit` — do not edit by hand.\n// **\n\npub const VERSION: string = "dev"\n' \
		> "$(VERSION_FILE)"
	@echo "version file restored to dev"

emit: gen-version
	lis emit

build-host: gen-version
	lis build

# zig_wrapper creates a shell wrapper that invokes zig cc with the given
# target triple.  Go's CGo driver requires CC to be a single executable.
define zig_wrapper
	@mkdir -p "$(WRAPPERS_DIR)"
	@printf '#!/bin/sh\nexec zig cc -target $(1) "$$@"\n' > "$(WRAPPERS_DIR)/$(2)"
	@chmod +x "$(WRAPPERS_DIR)/$(2)"
endef

# build-all cross-compiles all six platform targets.
# macOS targets use the native host toolchain; Linux and Windows use zig cc.
build-all: emit
	@mkdir -p "$(BUILD_DIR)" "$(WRAPPERS_DIR)"
	@echo "building darwin/arm64 (native) ..."
	@CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 \
		go build -C "$(TARGET)" -o "../$(BUILD_DIR)/$(BINARY)_darwin_arm64_$(VERSION)" .
	@echo "building darwin/amd64 (native) ..."
	@CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 \
		go build -C "$(TARGET)" -o "../$(BUILD_DIR)/$(BINARY)_darwin_amd64_$(VERSION)" .
	@echo "building linux/arm64 ..."
	$(call zig_wrapper,aarch64-linux-gnu.2.28,zcc-linux-arm64)
	@CC="$(PWD)/$(WRAPPERS_DIR)/zcc-linux-arm64" CGO_ENABLED=1 GOOS=linux GOARCH=arm64 \
		go build -C "$(TARGET)" -o "../$(BUILD_DIR)/$(BINARY)_linux_arm64_$(VERSION)" .
	@echo "building linux/amd64 ..."
	$(call zig_wrapper,x86_64-linux-gnu.2.28,zcc-linux-amd64)
	@CC="$(PWD)/$(WRAPPERS_DIR)/zcc-linux-amd64" CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
		go build -C "$(TARGET)" -o "../$(BUILD_DIR)/$(BINARY)_linux_amd64_$(VERSION)" .
	@echo "building windows/arm64 ..."
	$(call zig_wrapper,aarch64-windows,zcc-windows-arm64)
	@CC="$(PWD)/$(WRAPPERS_DIR)/zcc-windows-arm64" CGO_ENABLED=1 GOOS=windows GOARCH=arm64 \
		go build -C "$(TARGET)" -o "../$(BUILD_DIR)/$(BINARY)_windows_arm64_$(VERSION).exe" .
	@echo "building windows/amd64 ..."
	$(call zig_wrapper,x86_64-windows,zcc-windows-amd64)
	@CC="$(PWD)/$(WRAPPERS_DIR)/zcc-windows-amd64" CGO_ENABLED=1 GOOS=windows GOARCH=amd64 \
		go build -C "$(TARGET)" -o "../$(BUILD_DIR)/$(BINARY)_windows_amd64_$(VERSION).exe" .
	@echo "all platforms built."
	$(MAKE) restore-version

checksums:
	@echo "computing checksums ..."
	@cd "$(BUILD_DIR)" && for f in $(BINARY)_*; do \
		[ -f "$$f" ] && shasum -a 256 "$$f" | awk '{print $$1}' > "$$f.sha256" \
		&& echo "  $$f.sha256"; \
	done || true
	@echo "done."

release: build-all checksums
	@if ! gh auth status > /dev/null 2>&1; then \
		echo "error: gh is not authenticated — run 'gh auth login' first" >&2; exit 1; \
	fi
	@tag="v$(VERSION)"; \
	notes=$$(awk "/^## $(VERSION)/{found=1; next} found && /^## /{exit} found{print}" CHANGELOG.md); \
	[ -z "$$notes" ] && notes="Release $(VERSION)"; \
	prerelease=""; \
	case "$(VERSION)" in *-*) prerelease="--prerelease" ;; esac; \
	echo "creating release $$tag ..."; \
	gh release create "$$tag" \
		--title "$$tag" \
		--notes "$$notes" \
		$$prerelease; \
	echo "uploading artifacts ..."; \
	for f in "$(BUILD_DIR)"/$(BINARY)_* "$(BUILD_DIR)"/*.sha256; do \
		[ -f "$$f" ] || continue; \
		gh release upload "$$tag" "$$f"; \
		echo "  uploaded: $$(basename $$f)"; \
	done; \
	echo ""; \
	echo "release $$tag published."; \
	gh release view "$$tag" --web

# ---------------------------------------------------------------------------
# Gate tests
# ---------------------------------------------------------------------------

LEGACY         := $(TOOLCHAIN_TEST)/Build/toolchain_test.build/Debug/Browser.environment/Sources
OURS           := $(TOOLCHAIN_TEST)/Build/capp-build.build/Debug/Sources
LEGACY_RELEASE := $(TOOLCHAIN_TEST)/Build/toolchain_test.build/Release/Browser.environment/Sources
OURS_RELEASE   := $(TOOLCHAIN_TEST)/Build/capp-build.build/Release/Sources

gate:
	lis build
	"$(TARGET)/bin/$(BINARY)" build --mode debug "$(TOOLCHAIN_TEST)"
	python3 payload_oracle.py diff "$(LEGACY)/main.j" "$(OURS)/main.j"
	python3 payload_oracle.py diff "$(LEGACY)/AppController.j" "$(OURS)/AppController.j"

gate-release:
	lis build
	"$(TARGET)/bin/$(BINARY)" build --mode release "$(TOOLCHAIN_TEST)"
	python3 payload_oracle.py diff "$(LEGACY_RELEASE)/main.j" "$(OURS_RELEASE)/main.j"
	python3 payload_oracle.py diff "$(LEGACY_RELEASE)/AppController.j" "$(OURS_RELEASE)/AppController.j"

REF_DEBUG_BUNDLE    := $(TOOLCHAIN_REF)/Build/Debug/toolchain_test/Browser.environment/toolchain_test.sj
REF_RELEASE_BUNDLE  := $(TOOLCHAIN_REF)/Build/Release/toolchain_test/Browser.environment/toolchain_test.sj
OURS_DEBUG_BUNDLE   := $(TOOLCHAIN_TEST)/Build/Debug/toolchain_test/Browser.environment/toolchain_test.sj
OURS_RELEASE_BUNDLE := $(TOOLCHAIN_TEST)/Build/Release/toolchain_test/Browser.environment/toolchain_test.sj

gate-archive:
	lis build
	"$(TARGET)/bin/$(BINARY)" build --mode debug "$(TOOLCHAIN_TEST)"
	python3 payload_oracle.py diff "$(REF_DEBUG_BUNDLE)" "$(OURS_DEBUG_BUNDLE)"
	"$(TARGET)/bin/$(BINARY)" build --mode release "$(TOOLCHAIN_TEST)"
	python3 payload_oracle.py diff "$(REF_RELEASE_BUNDLE)" "$(OURS_RELEASE_BUNDLE)"

# ---------------------------------------------------------------------------
# Maintenance
# ---------------------------------------------------------------------------

clean:
	rm -rf "$(BUILD_DIR)" "$(WRAPPERS_DIR)"
	rm -rf $(TARGET)/vendor
	rm -f $(TARGET)/go.sum

bump-parse:
	@hash=$$(git -C "$(PARSE_DIR)" rev-parse HEAD) || exit 1; \
	upstream=$$(git -C "$(PARSE_DIR)" rev-parse '@{upstream}' 2>/dev/null); \
	if [ -z "$$upstream" ]; then \
		echo "error: capp-parse HEAD has no upstream — push the branch first"; exit 1; \
	fi; \
	if ! git -C "$(PARSE_DIR)" merge-base --is-ancestor "$$hash" "$$upstream"; then \
		echo "error: capp-parse HEAD ($$hash) is not pushed — push before pinning"; exit 1; \
	fi; \
	echo "resolving $(PARSE_MODULE)@$$hash ..."; \
	version=$$(cd "$(TARGET)" && go list -m "$(PARSE_MODULE)@$$hash" | awk '{print $$2}') || exit 1; \
	tmp=$$(mktemp); \
	sed "s|^\"$(PARSE_MODULE)\" = .*|\"$(PARSE_MODULE)\" = \"$$version\"|" lisette.toml > "$$tmp" \
		&& mv "$$tmp" lisette.toml; \
	git --no-pager diff -- lisette.toml; \
	lis run
